services:
  bank-api_database:
    container_name: bank-api_database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${DB_DOCKER_VOLUME_PATH}:/var/lib/postgresql/data

  bank-api_redis:
    container_name: bank-api_redis
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DOCKER_VOLUME_PATH}:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data:
