services:
  bank-api_database:
    container_name: bank-api_database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgres/data

  bank-api_redis:
    container_name: bank-api_redis
    image: redis/redis-stack
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
      - ${REDIS_INSIGHT_PORT}:8001
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data:
