services:
  postgres:
    container_name: postgres-container
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - bank-postgres:/var/lib/postgresql/data

volumes:
  bank-postgres:
