services:
  postgres:
    container_name: bank-api-container
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - bank-api:/var/lib/postgresql/data

volumes:
  bank-api:
