services:
  postgres-db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
